### PR TITLE
Zipkin

### PR DESCRIPTION
**Pull request by alsuren**
This is based on top of #20, so we probably want to review that first and get it merged.

The dapr zipkin integration manages to show single-hop dependencies between services, because all inter-service traffic goes via the sidecar. It wouldn't let you debug a call that gets threaded via multiple services though, because it doesn't have anything telling it "this downstream http request was made because we are handling this upstream http request". For this, you need to add instrumentation into the app.

This PR adds opentelemetry auto-instrumentation to link up express -> fetch within the slack api. This allows you to get traces like this:

Screenshot 2021-06-18 at 16 56 32

OpenTelemetry is a whole bunch of boilerplate that takes me all day to set up every time I set it up (and I've not even touched our logging or the rust service), because they insist on exposing all the complexity all the time. I really wish there was a simple package where you say "please instrument all the things you can find, and send them to zipkin with service name 'slack-ts'".

### CODE REVIEW

**Review by ceddlyburge — APPROVED** [review]
These changes don't look too bad either, although I can imagine it was fiddly to get right (and might be flaky). Certainly I don't really understand what tracer.ts is doing.

Again, I haven't tested it so let me know if you want me to.

Cheers, Cedd

**Comment by alsuren** [comment]
> These changes don't look too bad either, although I can imagine it was fiddly to get right (and might be flaky). Certainly I don't really understand what tracer.ts is doing.

Yeah, it's a bit of a pain. You have to load the entire opentracing ecosystem into your head once at the start of the project, and then again each time dependabot tries to make an incompatible set of package upgrades. I really wish someone would make a package that does it all for you (it could probably be a thin wrapper that lives in the dapr namespace, since all dapr projects will probably be set up in the same way). This would reduce the amount of complexity that you need to front-load on new projects.

The nodejs part will probably be fine, since it's all driven by auto-instrumentation of express and fetch. The rust one will probably need revisiting as we add more complexity.

I would really like to install a thing that can instrument calls to `console.log()` (I have a feeling that the azure sdk does this?), but I can't find one.

> Again, I haven't tested it so let me know if you want me to.

I think it should be fine. I suppose you will need to uninstall the slim version of dapr and install the one which deploys zipkin in docker, but otherwise I'm not expecting any problems.

**Comment by ceddlyburge** [comment]
> I would really like to install a thing that can instrument calls to console.log() (I have a feeling that the azure sdk does this?), but I can't find one.

Yep, logging to stdout is one of the 12 factor things. Feels like there must be something. I don't know of one either though ...

**Comment by alsuren** [comment]
> Yep, logging to stdout is one of the 12 factor things

unfortunately logging to stdout is not always compatible with distributed tracing, because the consumer of stdout won't know which context the log line comes from. I'm a big fan of logging to a framework, and then having the framework send the logs to stdout and syslogd/whatever in parallel. Much easier than trying to parse stdout.

**Pull request merged**
